# This is the base configuration of the server running at open-vsx.org.
# Properties containing secrets are not included here, e.g. spring.datasource
# for database access and ovsx.storage.azure for file storage access.
# Additional properties are loaded from the file provided with the
# DEPLOYMENT_CONFIG environment variable.
server:
  address: 0.0.0.0
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json,text/xml,application/xml,application/xml+rss,text/javascript
    min-response-size: 1024
spring:
  profiles:
    include: ovsx
 # config:
  #  import: file:${DEPLOYMENT_CONFIG}
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:postgres://postgrespw@localhost:49153
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  flyway:
    baseline-on-migrate: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  resources:
    cache:
      cachecontrol:
        max-age: 4h
        cache-public: true
  session:
    store-type: jdbc
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    oauth2:
      client:
        registration:
          eclipse:
            authorization-grant-type: authorization_code
            scope: openvsx_publisher_agreement, profile
        provider:
          eclipse:
            authorization-uri: https://accounts.eclipse.org/oauth2/authorize
            token-uri: https://accounts.eclipse.org/oauth2/token
            user-info-uri: https://accounts.eclipse.org/oauth2/UserInfo
            user-name-attribute: name
            user-info-authentication-method: header
management:
  server:
    port: 8081
  health:
    probes:
      enabled: true
org:
  jobrunr:
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
      worker-count: 2
    dashboard:
      enabled: false
    miscellaneous:
      allow-anonymous-data-usage: false
ovsx:
  storage:
    primary-service: azure-blob
  webui:
    frontendRoutes: "/extension/**,/user-settings/**,/admin-dashboard/**,/about,/publisher-agreement-*,/terms-of-use"
  eclipse:
    base-url: https://api.eclipse.org/
    publisher-agreement:
      version: 1
      timezone: US/Eastern
  publishing:
    require-license: true
  elasticsearch:
    enabled: true
    ssl: true
    relevance:
      rating: 0.2
      downloads: 1.0
      timestamp: 3.0
